name: CI smoke test
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Show hello
        run: |
          echo "GitHub Actions smoke test"
          echo "Commit: $GITHUB_SHA"
